# Generated by Django 5.0.2 on 2024-02-22 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gennotate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('type', models.CharField(max_length=40)),
                ('addToGallery', models.CharField(max_length=40)),
                ('annotations', models.TextField(max_length=1000)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gennotate.user')),
            ],
        ),
    ]
