# Generated by Django 5.0.2 on 2024-02-22 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gennotate', '0002_generatedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SegmentedImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('annotations', models.TextField(max_length=1000)),
                ('generatedImageId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gennotate.user')),
            ],
        ),
    ]
