# Generated by Django 5.0.2 on 2024-02-25 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gennotate', '0006_alter_generatedimage_addtogallery_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TestModel',
        ),
    ]
